-- 코드를 입력하세요
WITH CTE AS
    (SELECT *
     FROM USER_INFO
     WHERE YEAR(JOINED) = 2021)
SELECT
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT C.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT C.USER_ID) / (SELECT COUNT(*) FROM CTE), 1) AS PURCHASED_RATIO
FROM CTE C
LEFT JOIN ONLINE_SALE O ON C.USER_ID = O.USER_ID
WHERE O.SALES_DATE IS NOT NULL
GROUP BY YEAR, MONTH