-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT CHILD.ID, CTE.GENERATION + 1
    FROM ECOLI_DATA CHILD
    JOIN CTE ON CHILD.PARENT_ID = CTE.ID
)

SELECT
    COUNT(*) AS COUNT,
    GENERATION
FROM (
    SELECT CTE.ID, CTE.GENERATION
    FROM CTE
    LEFT JOIN ECOLI_DATA E ON CTE.ID = E.PARENT_ID
    WHERE E.ID IS NULL
) AS LEAF
GROUP BY GENERATION
ORDER BY GENERATION;