SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D 
JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE = S.CODE
WHERE D.SKILL_CODE & (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python')
OR D.SKILL_CODE & (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#')
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID;