-- 코드를 작성해주세요
SELECT
    SUM(G.SCORE) AS 'SCORE',
    G.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES E
INNER JOIN HR_DEPARTMENT D ON D.DEPT_ID = E.DEPT_ID
INNER JOIN HR_GRADE G ON G.EMP_NO = E.EMP_NO
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
