-- 코드를 작성해주세요
WITH SKILLS AS (
  SELECT D.ID, D.EMAIL, S.NAME, S.CATEGORY
  FROM DEVELOPERS D
  JOIN SKILLCODES S
    ON D.SKILL_CODE & S.CODE = S.CODE
),
GRADE_BASE AS (
  SELECT
    ID,
    EMAIL,
    MAX(CASE WHEN NAME = 'C#' THEN 1 ELSE 0 END) AS HAS_CS,
    MAX(CASE WHEN NAME = 'Python' THEN 1 ELSE 0 END) AS HAS_PYTHON,
    MAX(CASE WHEN CATEGORY = 'Front End' THEN 1 ELSE 0 END) AS HAS_FE
  FROM SKILLS
  GROUP BY ID, EMAIL
)
SELECT
  CASE
    WHEN HAS_CS = 1 THEN 'B'
    WHEN HAS_PYTHON = 1 AND HAS_FE = 1 THEN 'A'
    WHEN HAS_FE = 1 THEN 'C'
  END AS GRADE,
  ID,
  EMAIL
FROM GRADE_BASE
WHERE
  HAS_CS = 1 OR
  (HAS_PYTHON = 1 AND HAS_FE = 1) OR
  HAS_FE = 1
ORDER BY GRADE, ID;